# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="duration_days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="trip",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="price_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trip",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_style",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
